id: IC32B0675
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:14:30+00:00'
last_modified: '2022-06-08T09:35:52.173998+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10766
  title: ལེགས་པར་སྦྱར་བ་ལྷའི་སྐད་དང་གངས་ཅན་པའི་བརྡའ་ཤན་སྦྱར་བ་དྲི་བྲལ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    21E5:
      image_group_id: I1KG10768
      title: ''
      total_pages: 662
      order: 1
      base_file: 21E5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
